# Generated by Django 5.0 on 2025-10-07 03:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalogs_ca_is_acti_d798f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='catalogs.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item category link',
                'verbose_name_plural': 'Item category links',
                'ordering': ['category__name', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Base price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('categories', models.ManyToManyField(blank=True, related_name='menu_items', through='catalogs.ItemCategory', to='catalogs.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Menu item',
                'verbose_name_plural': 'Menu items',
            },
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price delta')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default selected')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_options', to='catalogs.menuitem', verbose_name='Menu item')),
            ],
            options={
                'verbose_name': 'Item option link',
                'verbose_name_plural': 'Item option links',
            },
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='catalogs.menuitem', verbose_name='Menu item'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalogs_op_is_acti_a1c067_idx')],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='menu_items', through='catalogs.ItemOption', to='catalogs.option', verbose_name='Options'),
        ),
        migrations.AddField(
            model_name='itemoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_options', to='catalogs.option', verbose_name='Option'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalogs_re_is_acti_8cbf00_idx')],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='catalogs.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['category', 'position'], name='catalogs_it_categor_ea41cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('menu_item', 'category'), name='uq_itemcategory_item_category'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='itemcategory_position_non_negative'),
        ),
        migrations.AddIndex(
            model_name='itemoption',
            index=models.Index(fields=['menu_item'], name='catalogs_it_menu_it_7ff558_idx'),
        ),
        migrations.AddIndex(
            model_name='itemoption',
            index=models.Index(fields=['option'], name='catalogs_it_option__16b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='itemoption',
            index=models.Index(fields=['is_default'], name='catalogs_it_is_defa_c0ba86_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.UniqueConstraint(fields=('menu_item', 'option'), name='uq_itemoption_item_option'),
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.CheckConstraint(check=models.Q(('price_delta__gte', 0)), name='itemoption_price_delta_non_negative'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_active'], name='catalogs_me_restaur_6bbe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available'], name='catalogs_me_is_avai_afba3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='menuitem_base_price_non_negative'),
        ),
    ]
